# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tristan Deloche's blog
email: tristandeloche@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog with no clear editorial line. Mostly tech stuff though.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.tristan.moe" # the base hostname & protocol for your site
twitter_username: _tristan971_
github_username:  Tristan971

# Build settings
markdown: kramdown
